### ISSUE TITLE
服务端怎么跑起来？

### ISSUE THREAD

**Issue by shangdibaozi** [ahuangege/lockstep#1]

**Comment by ahuangege** [comment]
https://github.com/ahuangege/mydog




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ahuangege/lockstep"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月16日(星期四) 上午10:06
收件人:&nbsp;"ahuangege/lockstep"<lockstep@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ahuangege/lockstep] 服务端怎么跑起来？ (#1)
